[package]
name = "tft-vision"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
